### PR TITLE
Improve popup UI, add favicons, update colors, and other design tweaks

### LINKED ISSUE #19: Set metadata (favicon, preview, etc.)
Trivial things, basically replace the Vite defaults. Also room to improve README etc.

### PR DESCRIPTION
**Pull request by quinnouyang**
Title. See [staging site](https://af94a923.rare-test.pages.dev/) for commit https://github.com/staylor7/rare-diseases/commit/7f111414016da73731b35476e5ffbcef15c41656 (note playback is broken, pending fixes in https://github.com/staylor7/rare-diseases/pull/32)

- Works on #24 (more to do)
- Resolves #19 (though preview is untested)

### CODE REVIEW

**Comment by staylor7** [comment]
Favicon is great! And for responsive design you should do whatever you think best.

**Comment by quinnouyang** [comment]
Reminder to self: redo favicon once new colors are in:)

**Comment by staylor7** [comment]
Here are the right colors finally!

ritu #bebada
indu #fcaea4
vasu	#81b2d2
rudra #fcbc73
veda #b3dd69
aditya #fdd8eb
dishi #d9d9d9
bana #bc80bd
bhrama #d5eecf
netra #ffed6f
agni #93d6ca
rishi #ffd9b3

**Comment by SallyXue-0114** [comment]
I basically combine the new features in main (pop up window, viola, etc) and the design in this branch (favicon, responsive). So although it still shows conflict, it's technically the latest and full version? You can pull the new changes and please lmk if there's any details I forget. If everything's fine I think there's a thing called branch overwrite or smth?

**Comment by quinnouyang** [comment]
@SallyXue-0114 Done! See [staging site](https://af94a923.rare-test.pages.dev/) for commit https://github.com/staylor7/rare-diseases/pull/27/commits/7f111414016da73731b35476e5ffbcef15c41656 (note playback is broken, pending fixes in #32)

**Comment by SallyXue-0114** [comment]
> @SallyXue-0114 Done! See [staging site](https://af94a923.rare-test.pages.dev/) for commit [7f11141](https://github.com/staylor7/rare-diseases/commit/7f111414016da73731b35476e5ffbcef15c41656) (note playback is broken, pending fixes in #32)

looks cool! I'm experiencing this error even after I refresh: "The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu". I assume this is the issue in #32?

**Comment by quinnouyang** [comment]
Yah (though I haven't merged the two branches so I can't be certain, but pretty sure #32 handles that). UI should be untouched by this issue

**Pull request merged**
