### PR TITLE
Fix breaking playback issues (asset loading, paths) and improve build configs

### LINKED ISSUE #29: Missing vasu chakra sound
There's only 11 in `assets/chakra` D:

### LINKED ISSUE #30: [STAGING] Viola audio has incorrect path and AudioContext can fail to initialize
## Issue

See [staging site](https://stephenandrewtaylor.net/rare-test/):
- `Failed to load resource: net::ERR_BLOCKED_BY_CLIENT`
- `Failed to load resource: the server responded with a status of 404`
- `The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu`
- `git bisect` shows problematic commit: https://github.com/staylor7/rare-diseases/commit/96adaae1b2561369265492624e0b786d84ad27c2

## To reproduce
- `git checkout 96adaae`
- In `vite.config.js`, replace `https://stephenandrewtaylor.net/rare-test` with `http://localhost:4173/rare-test`.
- `npm run build && npm run preview`
- See console and note failed playback

### LINKED ISSUE #33: [STAGING] Audio assets can be stuck pending from long server wait times
Pending JS assets (import statements) seem to block audio ones. Seems to be a server issue that is potentially resolvable in how we import these (get Vite to not optimize dynamic imports using JS?).

Here, we select the `bhrama` chakra, spam click its diseases, then exit out to the `netra` chakra and do the same. Notice how the load time for some of the disease JS assets block everything else.
image

~~Inconsistently (?) reproducable on Chrome and Safari, macOS. Browser limitation of 6 simultaneous requests?~~

## To reproduce
- Go to [staging](https://stephenandrewtaylor.net/rare-test/) (as of 10:31 CST 3/15/2024, build is approximately off of https://github.com/staylor7/rare-diseases/pull/32/commits/45a518bb29da112f6891b271304d185efa2fed8e)
- Open `Inspect` -> `Network` -> `Disable cache` (checked) -> `Media`/`Other` (optional, but filters network loads to our audio assets)
- **Quickly click** playback elements (viola, chakra, disease) and note that requests can be pending in a queue (though not necessarily loading one at a time)

~~## Related Links~~
- ~~https://stackoverflow.com/questions/39067482/chrome-requests-gets-stuck-on-pending~~
- ~~https://stackoverflow.com/questions/17004658/chrome-only-loading-6-html5-audio-tags~~

### Chrome
image

### Safari
image

### PR DESCRIPTION
**Pull request by quinnouyang**
See [staging site](https://d9688c80.rare-test.pages.dev//) for commit https://github.com/staylor7/rare-diseases/pull/32/commits/197a4879f0ab932097efba79750ba9c0b97b64d2

- Resolves #30 
- Resolves #33 (?)
- Resolves #29

### CODE REVIEW

**Comment by quinnouyang** [comment]
@SallyXue-0114 See this [staging site](https://3199f75b.rare-test.pages.dev/) on Cloudflare as of commit https://github.com/staylor7/rare-diseases/pull/32/commits/62e0ea4cf8f5d991881495b8c2414b97ad932bf9

**Comment by staylor7** [comment]
Staging site looks great! I have one question on the background chakra sounds. Before they loop back to the beginning, they fade out, then restart. Is it possible to have the chakra sounds loop without any silence in between?

**Comment by SallyXue-0114** [comment]
> @SallyXue-0114 See this [staging site](https://3199f75b.rare-test.pages.dev/) on Cloudflare as of commit [62e0ea4](https://github.com/staylor7/rare-diseases/commit/62e0ea4cf8f5d991881495b8c2414b97ad932bf9)

The link works perfectly on my end👍 no delay or loading problems.

**Comment by quinnouyang** [comment]
@staylor7 We're relying on the built-in [`loop` property](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/loop), which doesn't seem to allow for customizations such as crossfading. We'll need to build our own, issue in #31

**Comment by quinnouyang** [comment]
See [staging site](https://df833241.rare-test.pages.dev/) for commit https://github.com/staylor7/rare-diseases/pull/32/commits/05c882850da12a9759fc33372cd7aa1ea650ad85

**Pull request merged**
