### PR TITLE
Enable audio playback by hovering over

### PR DESCRIPTION
**Pull request by SallyXue-0114**

### CODE REVIEW

**Comment by quinnouyang** [comment]
@staylor7 What do the audio files in `sounds/` and `promoter_sounds_mp3/` correspond to? Do the order of the CSV rows correspond to the file indices of `promoter_sounds_mp3/`? (Sally added an index to the CSV relying on this assumption.)

**Comment by staylor7** [comment]
Yes, that’s right - the index of the csv rows is the same as the file numbers for each sound. Thanks Quinn!

**Comment by quinnouyang** [comment]
What about the 50 files in `sounds/`?

**Comment by staylor7** [comment]
Those were a first draft, sorry I should have probably deleted them!

**Pull request merged**
